const state = { tasks: [], current: null, catalog: null, loading: false, tab: 'preview' };
const $ = (id) => document.getElementById(id);
const api = async (path, options = {}) => { const response = await fetch(path, options); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || `Request failed (${response.status})`); return payload; };
const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));
const statusClass = (value) => String(value || '').replaceAll('_', '-');
const taskLabel = (task) => task.user_request.length > 42 ? `${task.user_request.slice(0, 42)}…` : task.user_request;
function toast(message) { const element = $('toast'); element.textContent = message; element.classList.remove('hidden'); setTimeout(() => element.classList.add('hidden'), 3200); }

async function refreshTasks() { try { const payload = await api('/api/tasks'); state.tasks = payload.tasks || []; renderTaskList(); if (state.current) await selectTask(state.current.task.task_id, false); $('health-label').textContent = 'online'; } catch (_) { $('health-label').textContent = 'offline'; } }
async function loadCatalog() { try { state.catalog = await api('/api/catalog'); } catch (error) { toast(error.message); } }
async function selectTask(taskId, replace = true) { try { state.current = await api(`/api/tasks/${encodeURIComponent(taskId)}`); $('empty-state').classList.add('hidden'); $('workspace').classList.remove('hidden'); renderCurrent(); if (replace) history.replaceState({}, '', `#${taskId}`); } catch (error) { toast(error.message); } }
function renderTaskList() { $('task-list').innerHTML = state.tasks.length ? state.tasks.map((task) => `<button class="task-row ${state.current?.task?.task_id === task.task_id ? 'selected' : ''}" data-task="${esc(task.task_id)}"><span class="task-row-dot ${statusClass(task.status)}"></span><span class="task-row-copy"><b>${esc(taskLabel(task))}</b><small>${esc(task.status.replaceAll('_',' '))}</small></span></button>`).join('') : '<div class="empty">No tasks yet.</div>'; document.querySelectorAll('[data-task]').forEach((button) => button.onclick = () => selectTask(button.dataset.task)); }
function renderCurrent() { const { task, messages=[], activity=[], attachments=[], artifacts=[], context } = state.current; $('page-title').textContent = taskLabel(task); $('task-status').textContent = task.status.replaceAll('_',' '); $('task-status').className = `status-pill ${statusClass(task.status)}`; $('task-summary').innerHTML = `<div class="summary-row"><span>Task ID</span><code>${esc(task.task_id)}</code></div><div class="summary-row"><span>Created</span><span>${new Date(task.created_at*1000).toLocaleString()}</span></div><div class="summary-row"><span>Commands</span><span>${task.command_history.length}</span></div>`; $('context-view').innerHTML = `<div>workspace&nbsp; ${esc(context?.workspace_root || './workspace')}</div><div>state-db&nbsp; local SQLite</div><div>controller&nbsp; DeepSeek</div><div>services&nbsp; ${esc((context?.connected_integrations || []).join(', ') || 'local only')}</div>`; renderConversation(messages, activity); renderAction(task); renderTab(task, attachments, artifacts, activity, context); renderTaskList(); }
function parseExecution(content) { try { return JSON.parse(content).execution_result; } catch (_) { return null; } }
function renderConversation(messages, activity) { const specialist = activity.filter((item) => ['delegated_call','model_result','tool_activity'].includes(item.type)).slice(-5).reverse().map((item) => { const payload=item.payload||{}; const label = item.type === 'delegated_call' ? `${payload.role || 'specialist'} is working` : item.type.replaceAll('_',' '); return `<div class="specialist-card"><span class="pulse"></span><span><b>${esc(label)}</b><small>${esc(payload.objective || payload.tool || payload.content || 'activity recorded')}</small></span></div>`; }).join(''); const transcript = messages.map((message) => { let content=message.content; let role=message.role; if (role==='assistant') { try { const parsed=JSON.parse(content); content=parsed.assistant_message || content; } catch (_) {} } const execution = role==='user' ? parseExecution(content) : null; if (execution) content=`<span class="execution-label">EXECUTION · ${esc(execution.task_status)}</span>${execution.output != null ? `<pre>${esc(JSON.stringify(execution.output,null,2))}</pre>` : ''}${execution.error ? `<div class="error-text">${esc(execution.error)}</div>` : ''}`; const citations = role==='assistant' && /(https?:\/\/[^\s]+)/.test(content) ? `<div class="citation-line">⌁ Sources detected in response</div>` : ''; return `<article class="message ${role}"><div class="message-label">${role==='assistant'?'DEEPSEEK':'YOU'}</div><div class="message-body">${role==='user' && !execution ? esc(content).replaceAll('\n','<br>') : content}${citations}</div></article>`; }).join(''); $('conversation').innerHTML = specialist + (transcript || '<div class="empty">Conversation is ready.</div>'); $('conversation').scrollTop = $('conversation').scrollHeight; }
function renderAction(task) { const card=$('action-card'); if(task.status==='waiting_for_user'){card.classList.remove('hidden');card.innerHTML=`<div class="action-kicker">DEEPSEEK NEEDS INPUT</div><strong>${esc(task.pending_input||'Please provide the requested information.')}</strong><div class="action-line"><input id="pending-input" placeholder="Your answer…"><button id="submit-input" class="primary">Continue →</button></div>`;$('submit-input').onclick=submitInput;return;} if(task.status==='waiting_for_approval'){const a=task.pending_approval||{};card.classList.remove('hidden');card.innerHTML=`<div class="action-kicker">APPROVAL REQUIRED</div><strong>${esc(a.summary||'DeepSeek requested approval')}</strong><p>${esc(a.impact||'')}</p><div class="action-line"><button id="approve-action" class="primary">Approve action</button><button id="reject-action" class="ghost">Cancel task</button></div>`;$('approve-action').onclick=()=>approveAction(a.action);$('reject-action').onclick=()=>cancelTask('Approval rejected');return;} if(task.status==='failed'){card.classList.remove('hidden');card.innerHTML=`<div class="action-kicker error-text">EXECUTION ERROR</div><strong>${esc(task.last_error||'The task failed.')}</strong><div class="action-line"><button id="retry-action" class="primary">Retry last command →</button><button id="cancel-action" class="ghost">Cancel</button></div>`;$('retry-action').onclick=retryTask;$('cancel-action').onclick=()=>cancelTask('Cancelled after error');return;}card.classList.add('hidden');card.innerHTML=''; }
function renderTab(task, attachments, artifacts, activity, context) { document.querySelectorAll('[data-tab]').forEach((button)=>{button.classList.toggle('active',button.dataset.tab===state.tab);button.onclick=()=>{state.tab=button.dataset.tab;renderTab(task,attachments,artifacts,activity,context);};}); const content=$('tab-content'); if(state.tab==='preview') content.innerHTML=`<div class="tab-hero"><span class="tab-symbol">◌</span><h3>Workspace preview</h3><p>Preview output from the current task will appear here when a local project or artifact is available.</p><span class="mini-chip">LOCAL WORKSPACE</span></div>`; if(state.tab==='code') content.innerHTML=`<div class="code-placeholder"><div class="code-line"><i>01</i><span><em>Open-Manus</em> will show project files here.</span></div><div class="code-line"><i>02</i><span>Ask DeepSeek to create or inspect a project.</span></div></div>`; if(state.tab==='browser') content.innerHTML=`<div class="browser-placeholder"><div class="browser-bar">⌕ https:// local preview</div><p>Browser tools are available through DeepSeek's research workflow when configured.</p></div>`; if(state.tab==='files') content.innerHTML=`<div class="file-list">${[...attachments.map((x)=>({...x,kind:'attachment'})),...artifacts.map((x)=>({...x,kind:'artifact'}))].map((file)=>`<div class="file-row"><span class="file-icon">${file.kind==='artifact'?'▣':'⌁'}</span><span><b>${esc(file.kind)}</b><small>${esc(file.path)}</small></span></div>`).join('')||'<span class="muted">No files registered yet.</span>'}</div><button id="add-file" class="ghost small">＋ Register local file</button>`; if(state.tab==='logs') content.innerHTML=`<div class="logs">${activity.slice().reverse().map((item)=>`<div><time>${new Date(item.created_at*1000).toLocaleTimeString()}</time><b>${esc(item.type)}</b><span>${esc(JSON.stringify(item.payload))}</span></div>`).join('')||'<span class="muted">No logs yet.</span>'}</div>`; if(state.tab==='settings') content.innerHTML=`<div class="settings"><label>Workspace<input value="${esc(context?.workspace_root||'./workspace')}" readonly></label><label>Persistence<input value="SQLite / local" readonly></label><label>Primary assistant<input value="DeepSeek controller" readonly></label><p>Settings are local to this laptop. Remote authentication is not enabled in this phase.</p></div>`; const add=$('add-file'); if(add) add.onclick=registerLocalPath; }
function openDrawer(view) { const data=state.catalog?.[view] || []; $('drawer-title').textContent=view.replaceAll('_',' ').toUpperCase(); $('drawer-content').innerHTML=Array.isArray(data)&&data.length?data.map((item)=>`<div class="drawer-item"><b>${esc(item.name||item.request||item.title||item.id)}</b><small>${esc(item.role||item.status||item.path||'')}</small></div>`).join(''):`<div class="empty">Nothing here yet. This surface is ready for the next integration.</div>`; $('catalog-drawer').classList.remove('hidden'); }
async function createTask(message){state.loading=true;try{const result=await api('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});await selectTask(result.task_id);await refreshTasks();}catch(e){toast(e.message);}finally{state.loading=false;}}
async function submitInput(){const value=$('pending-input')?.value.trim();if(!value)return;try{await api(`/api/tasks/${state.current.task.task_id}/input`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({value})});await selectTask(state.current.task.task_id,false);}catch(e){toast(e.message);}}
async function approveAction(action){try{await api(`/api/tasks/${state.current.task.task_id}/approve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});await selectTask(state.current.task.task_id,false);}catch(e){toast(e.message);}}
async function retryTask(){try{await api(`/api/tasks/${state.current.task.task_id}/retry`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await selectTask(state.current.task.task_id,false);}catch(e){toast(e.message);}}
async function cancelTask(reason){try{await api(`/api/tasks/${state.current.task.task_id}/cancel`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});await selectTask(state.current.task.task_id,false);}catch(e){toast(e.message);}}
async function registerLocalPath(){if(!state.current)return;const path=prompt('Local file path (already accessible to Open-Manus):');if(!path)return;try{await api(`/api/tasks/${state.current.task.task_id}/attachments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({attachment_id:`att-${Date.now()}`,path})});await selectTask(state.current.task.task_id,false);}catch(e){toast(e.message);}}
async function uploadFile(file){if(!state.current||!file)return;const form=new FormData();form.append('file',file);try{await api(`/api/tasks/${state.current.task.task_id}/attachments`,{method:'POST',body:form});await selectTask(state.current.task.task_id,false);toast('File uploaded to the local workspace.');}catch(e){toast(e.message);}}
$('composer').onsubmit=(event)=>{event.preventDefault();const input=$('message-input'),value=input.value.trim();if(!value||state.loading)return;if(state.current?.task.status==='waiting_for_user'){ $('pending-input').value=value;submitInput(); }else createTask(value);input.value='';};$('message-input').onkeydown=(event)=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();$('composer').requestSubmit();}};$('file-input').onchange=(event)=>uploadFile(event.target.files[0]);$('new-task').onclick=()=>{state.current=null;$('workspace').classList.add('hidden');$('empty-state').classList.remove('hidden');$('message-input').focus();};$('empty-new-task').onclick=()=>$('message-input').focus();$('close-drawer').onclick=()=>$('catalog-drawer').classList.add('hidden');document.querySelectorAll('[data-view]').forEach((button)=>button.onclick=()=>openDrawer(button.dataset.view));
(async function init(){await Promise.all([refreshTasks(),loadCatalog()]);const hash=location.hash.slice(1);if(hash)await selectTask(hash);setInterval(refreshTasks,5000);})();
